### ISSUE TITLE
Lab 1

### ISSUE THREAD

**Issue by JayCastro** [DS4PS/cpp-525-fall-2020#1]
Quick question. When we make our own variable I understand that treatment is the dummy variable and starts at the half way mark which is about 183. Does the count up for time since also start at the half way mark or do you want it to count up starting in the dummy variable. Im assuming the answer is no for the latter but I want to make sure.

**Comment by Dselby86** [comment]
The Time Since is days since the treatment. So the binary variable should be a 0 for the days prior to the new bus schedule, and the 1 for the day since the treatment was implemented.  Then days since should be a 0 before the treatment (May 1st), and a 1 on May 1st and count up until the end of the year.

Also, the lab instructions say this: "Data were collected from January 1st to December 31st. The intervention was implemented on May 1st (day 121 is the first day of the new schedule)." So make sure you start the treatment on day 121 and not 183.

**Comment by JayCastro** [comment]
I figured that out but thank you!
