### ISSUE TITLE
Lab 1 Coefficients

### ISSUE THREAD

**Issue by Niagara1000** [DS4PS/cpp-525-fall-2020#4]
Hi Prof @Dselby86 ,

I am stuck on the lab question: **Q2d: Which coefficient represents the immediate effect of the policy? (5 points)**

I have been trying for a while, and I've only come up with this answer. I was trying to not give away the answer, but I really had to ask if this explanation was accurate or not, since I cannot proceed with the lab if this question is answered incorrectly. I'm sorry if it gives away the answer

This is what I've written. 

> "The immediate effect of the policy is represented by the coefficient B2, i.e., the Treatment coefficient.
It represents how the outcome level has changed from the last observation before the intervention to the first one after. [Source](https://ds4ps.org/pe4ps-textbook/docs/p-020-time-series.html#fig:f1). In this case, the slope of the line has not changed significantly, because the value of the Treatment coefficient is "21.68 (SE=15.02)" without the significance stars, and hence, the immediate effect is not significant. This means the immediate effect is almost non-existent. The program had little to no effect on increasing bus transportation."

Is my explanation correct?

**Comment by Dselby86** [comment]
The treatment variable is the binary variable, it shows the immediate effect of the treatment. The meaning of the variable is up for you to decipher. 

Think about this in a medical context. Say I had a headache, and I am recording my pain level every 15 minutes.  After two hours of having a headache, I decided to take some aspirin.  Every time period before the aspirin is 0, every time period after I take the aspirin is a 1.  I don't immediately feel better, but after 30 minutes I do.

If I'm only including the treatment variable in this example, that is only the average head pain I feel before and after the treatment. If I am controlling for the time trends, then there isn't an instant effect of the asprin.  The coefficient of the asprin treatment will not be significantly different than 0. But in the time since I took the aspirin I will gradually feel better, meaning the time since variable will be signficantly differnent from 0.

**Comment by Niagara1000** [comment]
> If I'm only including the treatment variable in this example, that is only the average head pain I feel before and after the treatment. If I am controlling for the time trends, then there isn't an instant effect of the asprin. The coefficient of the asprin treatment will not be significantly different than 0. But in the time since I took the aspirin I will gradually feel better, meaning the time since variable will be signficantly differnent from 0.

Prof @Dselby86 ,
I'm sorry, could you explain this part again?

**Comment by Dselby86** [comment]
Sure. The Time Series model has three independent variables: Time, Treatment, Time Since.

The time variable controls for the underlying time trend. In the case of the lab it estimates if more or less people ride the bus over the course of the year, for the headache example it tracks how you are feeling throughout the day.

The Treatment checks if the treatment or intervention was implemented.  For the Bus plan it was the new bus schedule.  In the case of a headache, it is whether you have taken asprin. In the regression model this estimate is the instant effect of the treatment.

The Time Since variable measures how long it has been since the treatment has gone into effect.  This lets you estimate the effect of the treatment over time. So if this value is signficicant it means that each that goes past increases or decreases the effect of the treatment

If the treatment variable is significant that implies that the new bus schedule instantly had an effect, or taking medicine instantly made you feel better.  The Time Since variable tells us what the long term effect of the treatment is.  If you remove the Time Since variable, that will give you the average effect of the treatment.
