### ISSUE TITLE
Lab 2, Q4e

### ISSUE THREAD

**Issue by RTrehern-ASU** [DS4PS/cpp-525-fall-2020#6]
Dr. Selby,
Can you point me in the direction of where to find the formula to calculate "predictions regarding the size of secular trends" in the Interrupted Time Series Model?  I was able to find it for the Diff-in-Diff model, but am unsure how to compare the two.

**Comment by JayCastro** [comment]
ID like to know also

**Comment by lecy** [comment]
It is not about a formula as much as it is about interpretation of models. 

The secular trends (gains independent of the treatment) are captured by both models in slightly different ways. 

Since the interrupted time series is a reflexive model trend is measured by a slope coefficient prior to the treatment. 

The diff-in-diff uses a comparison group (a non-equivalent control group) to capture trend - i.e. changes independent of receiving the treatment, using a pre-post comparison within that group. 

There is no formula - you have everything you need in the regression models. 

You need to think critically about which what the coefficients actually represent, and how they are used to model the data.

**Comment by lecy** [comment]
One hint that might help you - what is the unit of time in the difference-in-difference model? When is the pre-intervention measure taken, and how much time passes before the post-treatment period? 

Similar, what does one-unit represent in the time series? 

How would you translate from one to another then?

**Comment by RTrehern-ASU** [comment]
Thank you for clarifying.  I think I understand what is being asked now.
